export const STORE_DEPLOYMENTS: string = "STORE_DEPLOYMENTS";
export const DEPLOY_CROSSCHAIN_DEPLOYER: string = "DEPLOY_CROSSCHAIN_DEPLOYER";
export const VERIFY_CROSSCHAIN_DEPLOYER: string = "VERIFY_CROSSCHAIN_DEPLOYER";
